import urllib2
import urllib
from scrape_police_data import read_heatmap_file

def fromIncidentFile(filename,size=(500,400)):
	'''Takes size tuple, csv file of incident data (as generated by scrape_police_data).
	Size tuple defaults to 500x400.'''
	pass

def fromHeatmapFile(filename,size=(500,400)):
	params = read_heatmap_file(filename)
	print type(params)
	print params[:5]
	return _requestMap(size,*params)

def fromIncidents(size=(500,400),*args):
	'''Tales size tuple, Incidents
	Size tuple defaults to 500x400'''
	params = tuple([(incident.coords['lat'],incident.coords['lng']) for incident in filter(lambda x: x.coords != (None, None),args)])
	return _requestMap(size,*params)

def fromTuples(size=(500,400),*args):
	'''Takes (lat,long) tuples
	Size tuple defaults to 500x400'''
	return _requestMap(size,*args)

def _requestMap(size=(500,400),*args):
	'''Takes (sizex,sizey) and (lat,long) tuples. Size defaults to 500 by 400'''
	paramstring = 'http://maps.googleapis.com/maps/api/staticmap?sensor=false&size=%s&visible=' %(str(size)[1:-1].replace(' ',''))
	delimiter = '%7C'
	paramstring += delimiter.join([','.join(arg) for arg in args])
	paramstring = urllib.urlencode(paramstring)
	print "Getting map from: " + paramstring
	img = urllib2.urlopen(paramstring).read()
	return img
