import urllib2
import urllib
import cStringIO
import math
from PIL import Image
from scrape_police_data import read_heatmap_file

def fromIncidentFile(filename,width=500):
	'''Takes width, csv file of incident data (as generated by scrape_police_data).
	Width defaults to 500'''
	pass

def fromHeatmapFile(filename,width=500):
	params = tuple(read_heatmap_file(filename))
	return _requestMap(width,*params)

def fromIncidents(width=500,*args):
	'''Tales width, Incidents
	Width defaults to 500'''
	params = tuple([(incident.coords['lat'],incident.coords['lng']) for incident in filter(lambda x: x.coords != (None, None),args)])
	return _requestMap(width,*params)

def fromTuples(width=500,*args):
	'''Takes (lat,long) tuples
	Width defaults to 500'''
	return _requestMap(width,*args)

def _requestMap(width=500,*args):
	'''Takes width and (lat,long) tuples. 
	Width defaults to 500'''
	#paramstring = 'http://maps.googleapis.com/maps/api/staticmap?sensor=false&size=%s&visible=' %(str(size)[1:-1].replace(' ',''))
	size = (width,_get_height(width,args))
	paramstring = 'http://maps.googleapis.com/maps/api/staticmap?visible=STUFF_HERE&size=MORE_STUFF&sensor=false'
	paramstring = paramstring.replace("MORE_STUFF",str(size[0]) + 'x' + str(size[1]))
	#example = "50,30%7C50.5,30.5"
	delimiter = '%7C'
	visible = delimiter.join([','.join(arg) for arg in args])
	#paramstring = urllib.quote(paramstring)
	#paramstring = paramstring.replace('-','%2D')
	paramstring = paramstring.replace('STUFF_HERE',visible)
	print "Getting map from: " + paramstring
	img = urllib2.urlopen(paramstring).read()
	img = Image.open(cStringIO.StringIO(img)).convert("RGB")
	return img

def _get_height(width,tuplelist):
	tuplelist = filter(lambda x: x != (), tuplelist)
	lats = [float(item[0]) for item in tuplelist]
	lngs = [float(item[1]) for item in tuplelist]
	latmin = min(lats)
	latmax = max(lats)
	lngmin = min(lngs)
	lngmax = max(lngs)
	latdelta = latmax - latmin
	lngdelta = lngmax - lngmin
	height = (latdelta / lngdelta) * width
	return int(math.ceil(height))

def convert_to_range(width,height,tuplelist):
	tuplelist = filter(lambda x: x != (), tuplelist)
	lats = [float(item[0]) for item in tuplelist]
	lngs = [float(item[1]) for item in tuplelist]
	latmin = min(lats)
	latmax = max(lats)
	lngmin = min(lngs)
	lngmax = max(lngs)
	oldlatrange = latmax - latmin
	newlatrange = height
	oldlngrange = lngmax - lngmin
	newlngrange = width
	convert_lat = lambda oldval: (((oldval - latmin) * newlatrange) / oldlatrange)
	convert_lng = lambda oldval: (((oldval - lngmin) * newlngrange) / oldlngrange)
	tuplelist = [(convert_lat(t[0]),convert_lng(t[1])) for t in tuplelist]
	return tuplelist

def pixelate_coords(tuplelist):
	return [(int(round(t[0])),int(round(t[1]))) for t in tuplelist]

def plot_coords(tuplelist,immap,color=(255,255,255)):
	for t in tuplelist:
		try:
			immap.setpixel(t,color)
		except:
			pass
	return immap

def get_coord_tuples(heatmap_filename):
	tuplelist = filter(lambda x: x != (), read_heatmap_file(heatmap_filename))
	tuplelist = [(float(item[0]),float(item[1])) for item in tuplelist]
	return tuplelist

def plot_heatmap(heatmap_filename,color=(255,255,255)):
	im = fromHeatmapFile(heatmap_filename)
	h = get_coord_tuples(heatmap_filename)
	h = convert_to_range(im.size[1],im.size[0],h)
	h = pixelate_coords(h)
	print h
	im = plot_coords(h,im,color)
	return im
