application: saferroute
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index\.html
- url: /css/stylesheet.css
  static_files: css/stylesheet.css
  upload: css/stylesheet\.css
- url: /js/jquery-1.9.1.min.js
  static_files: js/jquery-1.9.1.min.js
  upload: js/jquery-1\.9\.1\.min\.js
- url: /js/heatmap_data_filtered.js
  static_files: js/heatmap_data_filtered.js
  upload: js/heatmap_data_filtered\.js

- url: /.*
  script: saferroute.py
