application: saferroute
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index\.html
- url: /mobile
  static_files: templates/mobile.html
  upload: templates/mobile\.html
- url: /heatmap
  static_files: templates/heatmap.html
  upload: templates/heatmap\.html
- url: /api_documentation
  static_files: templates/api_documentation.html
  upload: templates/api_documentation\.html
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico
- url: /css/stylesheet.css
  static_files: css/stylesheet.css
  upload: css/stylesheet\.css
- url: /css/mobi_style.css
  static_files: css/mobi_style.css
  upload: css/mobi_style\.css
- url: /js/jquery-1.9.1.min.js
  static_files: js/jquery-1.9.1.min.js
  upload: js/jquery-1\.9\.1\.min\.js
- url: /js/heatmap_data_filtered.js
  static_files: js/heatmap_data_filtered.js
  upload: js/heatmap_data_filtered\.js
- url: /assets/pw_maze_white.png
  static_files: assets/pw_maze_white.png
  upload: assets/pw_maze_white\.png
- url: /assets/logo_mobile.png
  static_files: assets/logo_mobile.png
  upload: assets/logo_mobile\.png

- url: /.*
  script: saferroute.py
